language: node_js

node_js:
  - 8

script:
  - npm run internal:test
  - printf "n\nn" | npm run build
  - npm test

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules